### ISSUE TITLE
train.py file is gone along with others

### ISSUE THREAD

**Issue by eyalbetzalel** [EugenHotaj/pytorch-generative#19]
Hi,

Some of the files seem to be miss and the code is not functioning without them. 

Can you please upload them back so we can continue using this wonderful framework? 

Thanks, 
EB

**Comment by EugenHotaj** [comment]
Oops, I removed `train.py` in 37fa2762e1a423b4de4ae82a22d6707a4f1aa492 since I (incorrectly) assumed no one was using it. I've added it back in c9a0cab1793a25d2aa2826b4cf0adad04b6351e9. Thanks for your patience!

What other files are missing for you, I don't recall removing anything else recently?

**Comment by eyalbetzalel** [comment]
Hi,

Thanks!

I got this error : 

>     
```
loss = self._loss_fn(x, y, preds)
  File "train.py", line 46, in loss_fn
    return criterion(preds, x).sum(dim=1).mean()
  File "/home/dsi/eyalbetzalel/pytorch-generative/env/pytorch_gen_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dsi/eyalbetzalel/pytorch-generative/env/pytorch_gen_venv/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 516, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/dsi/eyalbetzalel/pytorch-generative/env/pytorch_gen_venv/lib/python3.7/site-packages/torch/nn/functional.py", line 2379, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1
```

**Comment by EugenHotaj** [comment]
Ah I see. I changed the models a while back (591b77f5aeb7e7147fd451b531916a8dec462516) to return logits instead of probabilities. I've fixed the `train.py` file to handle this now in 7775726ce9f00ead0778ee3e730d7a281b1ffce9 (use `BCEWithLogitsLoss` instead of `BCELoss`).

**Comment by eyalbetzalel** [comment]
Well, I succeed in training a PixelSnail model on MNIST and sample from it - but it seems like the training process is running on CPU rather on the GPU. am I missing anything? 

Thanks! 

@EugenHotaj

**Comment by EugenHotaj** [comment]
Glad to hear it!
