### ISSUE TITLE
Applying Style Transfer to a GIF

### ISSUE THREAD

**Issue by thistleknot** [EugenHotaj/pytorch-generative#25]
forgive me if you've already made this possible.
I was looking at a small gif and I thought to myself it would be cool to stylize each picture in the gif.

I realized I could do this myself by saving the pictures individually and then applying the process one at a time.  I remember you saying something about input images can be processed similar to how you did the multiple style images.

Forgive me if the feature is already there and I just don't know how to set it up properly.  But if it's not there (or is) can you assist in either an explanation or save this as a pending feature?

It would be pretty cool to redo gif's using this.

**Comment by EugenHotaj** [comment]
Hey @thistleknot,

Do you mean all images in the GIF have the same style? Or each image has a different style?

In either case, you should be able to do what you want by just applying the style transfer in a loop, e.g.:

```python
styled_images = []
for image in gif_images:
  styled_image = ... # run style transfer
  styled_images.append(styled_image)
# make gif with styled_images 
```

A gif is basically a bunch of images, so it should be fairly straightforward to load a gif into the Colab, get the individual images, run style transfer on each one, then create a new gif using the resulting images. 

That being said, what's implemented in pytorch-generative is just vanilla neural style transfer. There are follow up works which apply style transfer to video. These run a lot faster than the for loop and take extra care to make sure the style is temporally coherent. You may want to look into these as I suspect you'll get much better results for gifs (and videos).

**Comment by thistleknot** [comment]
all images same style.
I am aware of the video methods (only conceptually, not any experience with it).  This was exactly what I was looking to do.  Apply the same style to a set of different images that are slightly moving (i.e. extracted jpg's from a gif).
