### ISSUE TITLE
How to run the style_transfer notebook without square images

### ISSUE THREAD

**Issue by RandallJEllis** [EugenHotaj/pytorch-generative#27]
In the style_transfer notebook, there is a `size` argument in the `colab_utils.load_image` function that resizes the images into squares (i.e., makes the dimensionality of the length and width the same). This leads to the outputs having square dimensions and I'd rather avoid this, but when I remove this argument and execute the `run_style_transfer` function, I get the following error:

```
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: UserWarning: Using a target size (torch.Size([1, 256, 256, 161])) that is different to the input size (torch.Size([1, 256, 311, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-64-2ce60ed3a286> in <module>()
     23     content_weight=1.,
     24     style_weight=1000.,
---> 25     log_steps=250)

7 frames
/usr/local/lib/python3.7/dist-packages/torch/functional.py in broadcast_tensors(*tensors)
     72     if has_torch_function(tensors):
     73         return handle_torch_function(broadcast_tensors, tensors, *tensors)
---> 74     return _VF.broadcast_tensors(tensors)  # type: ignore
     75 
     76 

RuntimeError: The size of tensor a (256) must match the size of tensor b (161) at non-singleton dimension 3
```

I'm wondering if there is a way to run the style transfer (which is of excellent quality) without resizing the content and style images into square dimensions.

**Comment by RandallJEllis** [comment]
> @RandallJEllis I believe the images can be of non-square but they do need to have the same dimensions, otherwise computing the losses will not work. One easy thing to do is resize the images to be the same dimensions, though this will throw off the aspect ratio. If you want to keep the aspect ratio the same, you can either pad or crop one of the images.

Thank you for the fast response. I made the style image (larger of the two) the same dimensions as the content image and I get the following error: 

```
ValueError: input_size (1024, 644) cannot be smaller than crop size tensor([[644., 664.]]) in any dimension.
```

I'm sure this is related to what you said about padding/cropping. Do you have any sample code to do either of these things?

**Comment by EugenHotaj** [comment]
Looks like an issue with the image augmentation actually. It might not work for non-square images, I will try to take a closer look.

In the meantime, you could try disabling the augmentation (which might give you slightly worse results). It should be as simple as changing `model(transform(input_img))` to `model(input_img)` in the `run_style_transfer` function.

**Comment by RandallJEllis** [comment]
Thank you! Replacing that line makes it run properly when the content and style images have the same dimensions, but still getting the original error if they're both kept at their starting dimensions.

**Comment by EugenHotaj** [comment]
I'll keep this open for a bit until the augmentation issue is fixed. Thanks for reporting it!
