### ISSUE TITLE
Are pretrained weights for any of these models in repo available anywhere?

### ISSUE THREAD

**Issue by ethancaballero** [EugenHotaj/pytorch-generative#29]

**Comment by EugenHotaj** [comment]
Unfortunately, I have not saved the model parameters anywhere. However, each model contains a `reproduce` function with all the hyper-parameters necessary to reproduce our results. The README contains a [walkthrough](https://github.com/EugenHotaj/pytorch-generative#reproducing-results) of how to reproduce results.
