### ISSUE TITLE
Positional encoding is replicated across all channels.

### ISSUE THREAD

**Issue by mattiasxu** [EugenHotaj/pytorch-generative#31]
https://github.com/EugenHotaj/pytorch-generative/blob/master/pytorch_generative/nn/attention.py

Hi! I was wondering why the shape of the positional encoding is what it is.

I thought 2 channels were enough, one channel for the encoding in the first dimension, and one channel for the encoding in the second dimension. Now, the positional encoding has C duplicates of each.

Thanks!

**Comment by EugenHotaj** [comment]
Great catch, thanks!

I don't remember exactly why this was replicated per channel but it seems that's not longer relevant. Will send out a fix shortly.
